
// ---------------------------------------------
// This file was generated by libmaker.py
// Project: DeviceModule
// ---------------------------------------------

#ifndef DEVICEMODULE_H
#define DEVICEMODULE_H

#include <Arduino.h>
#include <ArduinoJson.h>
#include <ChronosESP32.h>
#include <SensorPCF8563.hpp>
#include <Timber.h>
#include <Wire.h>
#include <cstdint>

#include "HealthModule.h"
#include "MotionModule.h"
#include "StorageModule.h"

#define CHRONOS_WATCHY_MAJOR 1
#define CHRONOS_WATCHY_MINOR 2
#define CHRONOS_WATCHY_PATCH 0

#define CHRONOS_WATCHY_BUILD "20260417"

#ifdef WATCHY_V3
#define BATT_ADC_PIN 9
#else
#define BATT_ADC_PIN 34
#endif

#define READ_INTERVAL_SEC 60
#define MAX_NOTIFICATIONS 20

#define MAX_RECORD_DAYS 14

#define TIMER_INFINITE -1

#define SETTINGS_FILE "/settings.json"
#define WEATHER_FILE "/weather.json"
#define NOTIFICATIONS_FILE "/notifications.json"
#define CONTACTS_FILE "/contacts.json"
#define QR_FILE "/qr.json"

#define BATTERY_FOLDER "/battery"

#define WATCH_NAME "Watchy"

#define SECONDS_TO_MS(s) ((s) * 1000UL)
#define MINUTE_TO_S(mn) ((mn) * 60)

struct SettingTime {
  uint8_t startHour;
  uint8_t startMinute;
  uint8_t endHour;
  uint8_t endMinute;
  uint8_t interval;
  bool enabled;
};

enum SettingsType { ST_QUIET, ST_SLEEP, ST_SEDENTARY, ST_WATER };

enum Units { UT_METRIC, UT_IMPERIAL };

enum Temperature { TP_CELSIUS, TP_FARENHEIT };

class DeviceModule {
public:
  // accessible from outside the class
  DeviceModule(ChronosESP32 &watch, StorageModule &storage,
               MotionModule &motion, HealthModule &health); // constructor
  ~DeviceModule();                                          // destructor

  void begin();
  void update();

  void initBLE();

  String getAddress();

  float getMilliVolts();
  int getBattery();
  void updateBattery();

  void setRTC();

  void sleepTimerStart(long seconds);
  bool sleepTimerStop();
  long sleepTimerDuration();
  bool sleepTimerEnded();
  String sleepTimerLeft();

  void setHourly(bool enabled);
  void set24hr(bool enabled);
  void setLanguage(uint8_t id);
  void setRTW(bool enabled);
  void setTempUnit(Temperature unit);
  void setUnits(Units unit);
  void setSettings(SettingsType type, SettingTime setting);

  bool getHourly();
  bool get24hr();
  uint8_t getLanguage();
  bool getRTW();
  String getTempUnit();
  Units getUnits();
  SettingTime getSettings(SettingsType type);

  void handleConfigs(Config config, uint32_t a, uint32_t b);
  void handleNotification(Notification notification);

  void setBLEInterval(int minutes);
  int getBLEInterval();

  String getDistanceUnit();
  int convertTemp(int degrees);

  String settingName(SettingsType type);
  bool isSettingActive(SettingsType type);

  void saveSettings();

  void refreshWeather();
  void saveWeather();

  void setWatchface(String path);
  String getWatchface();

  void refreshNotifications();
  void saveNotifications();
  int getNotifications(Notification *array, size_t max);
  void clearNotifications();

  void saveQR();
  void refreshQR();
  int getQR(Contact *array, size_t max);

  void saveContacts();
  void refreshContacts();
  int getContacts(Contact *array, int *sos, size_t max);

  void setRTCAlarm(DateTime dt);
  long secondsUntil(uint8_t hour, uint8_t minute);

  Weather getCurrent();
  int getForecast(Weather *array, size_t max);

  int yearDay(int year = -1, int day = -1);

  String getDay(int day);
  String getMonth(int month);
  String getDayLong(int day);
  String getMonthLong(int month);
  String getCity();

  void saveHourlyBattery(int year, int month, int day, int hour,
                         int batteryPercent);
  String readDailyBattery(int year, int month, int day);
  String getDailyBatteryLevels(int year, int month, int day);

  uint32_t getBatteryRecords(int32_t *array, int start, int count, int year,
                             int month, int day);
  uint32_t getBatteryRecordsToday(int32_t *array, int start, int count);

  uint32_t getStepsRecords(int32_t *array, int start, int count, int year,
                           int month, int day);
  uint32_t getStepsRecordsToday(int32_t *array, int start, int count);

  DateTime getDateDifference(DateTime date, int32_t diff);
  DateTime getDateTime();

  void setNavigationIconCallback(void (*callback)(uint8_t *, bool));
  void setNavigationDataCallback(void (*callback)(String, String, String,
                                                  bool));

  bool isNavigationActive();
  void setInvertDisplay(bool invert);
  bool getInvertDisplay();

  void setPhoneInfo();
  DateTime getSyncTime();
  String getLastSync();
  String getAppVersion();
  int getAppCode();
  uint8_t getPhoneBattery();
  bool isPhoneCharging();

  void checkHourlyData();
  void setSyncData(bool state);
  bool shouldSyncData();

  void houseKeeping();

  String getBuild();
  String getVersion();

  StorageModule &mStorage;
  ChronosESP32 &mWatch;
  MotionModule &mMotion;
  HealthModule &mHealth;

protected:
  // cannot be accessed from outside the class, however, they can be accessed in
  // inherited classes
private:
  ChronosTimer sleepTimer;

  SensorPCF8563 rtc;

  JsonDocument weatherDoc;
  JsonDocument settingsDoc;
  JsonDocument notificationsDoc;
  JsonDocument contactsDoc;
  JsonDocument qrDoc;

  bool notificationsUpdated;
  bool weatherUpdated;
  bool settingsUpdated;
  bool contactsUpdated;
  bool qrUpdated;

  bool synced;
  unsigned long lastUpdateTime;
  unsigned long lastRead;
  float milliVolts;

  Navigation nav;
  bool navChanged = false;
  bool navIcChanged = false;
  uint32_t navIcCRC = 0xFFFFFFFF;

  bool sync_data = false;

  void (*navigationIconCallback)(uint8_t *, bool) = nullptr;
  void (*navigationDataCallback)(String, String, String, bool) = nullptr;

  bool isLeapYear(uint32_t year);
  uint8_t daysInMonth(uint8_t month, uint32_t year);
  void arrayRemove(JsonArray &array, String value);
  void clearOldRecordFiles(String path);

  String getQrApp(int index);
};

#endif
