
// ---------------------------------------------
// This file was generated by libmaker.py
// Project: ButtonModule
// ---------------------------------------------

#include "ButtonModule.h"

Button2 ButtonModule::up;
Button2 ButtonModule::down;
Button2 ButtonModule::menu;
Button2 ButtonModule::back;

ButtonModule *ButtonModule::instance = nullptr;

/**
 * @brief Constructor for ButtonModule
 *
 */
ButtonModule::ButtonModule()
{
    instance = this;
}

/**
 * @brief Destructor for ButtonModule
 *
 */
ButtonModule::~ButtonModule()
{
}

/**
 * @brief begin
 * Configure buttons and create task for reading buttons
 */
void ButtonModule::begin()
{
    up.begin(BUTTON_UP, INPUT, false);
    down.begin(BUTTON_DOWN, INPUT, false);
    menu.begin(BUTTON_MENU, INPUT, false);
    back.begin(BUTTON_BACK, INPUT, false);

    up.setID(BT_UP);
    down.setID(BT_DOWN);
    menu.setID(BT_MENU);
    back.setID(BT_BACK);

    up.setLongClickTime(LONG_CLICK_MS);
    down.setLongClickTime(LONG_CLICK_MS);
    menu.setLongClickTime(LONG_CLICK_MS);
    back.setLongClickTime(LONG_CLICK_MS);

    up.setClickHandler(buttonHandler);
    down.setClickHandler(buttonHandler);
    menu.setClickHandler(buttonHandler);
    back.setClickHandler(buttonHandler);

    up.setDoubleClickHandler(buttonHandler);
    down.setDoubleClickHandler(buttonHandler);
    menu.setDoubleClickHandler(buttonHandler);
    back.setDoubleClickHandler(buttonHandler);

    up.setLongClickHandler(buttonHandler);
    down.setLongClickHandler(buttonHandler);
    menu.setLongClickHandler(buttonHandler);
    back.setLongClickHandler(buttonHandler);

    up.setLongClickDetectedHandler(longPressDetect);
    down.setLongClickDetectedHandler(longPressDetect);
    menu.setLongClickDetectedHandler(longPressDetect);
    back.setLongClickDetectedHandler(longPressDetect);

    // Create event queue
    buttonQueue = xQueueCreate(10, sizeof(ButtonEvent));

    // Create task for button polling
    xTaskCreatePinnedToCore(
        buttonTask,
        "ButtonTask",
        4096,
        this,
        1,
        NULL,
        1 // or 0/1 depending on core preference
    );
}

/**
 * @brief update
 * Update button queue events when available
 */
void ButtonModule::update()
{
    if (!buttonQueue)
        return;

    ButtonEvent evt;
    while (xQueueReceive(buttonQueue, &evt, 0))
    {
        if (buttonCallback)
            buttonCallback(evt);
    }
}

/**
 * Function for the button task
 * @param param params for the task
 */
void ButtonModule::buttonTask(void *param)
{
    ButtonModule *self = static_cast<ButtonModule *>(param);

    for (;;)
    {
        self->up.loop();
        self->down.loop();
        self->menu.loop();
        self->back.loop();

        vTaskDelay(pdMS_TO_TICKS(20)); // 50Hz polling
    }
}

/**
 * Button handler function
 * @param button button
 */
void ButtonModule::buttonHandler(Button2 &button)
{
    if (!instance)
        return;

    int id = button.getID();
    if (id < BT_BACK || id > BT_DOWN)
        return;

    ButtonEvent evt;
    evt.type = (ButtonType)button.getID();
    evt.click = button.getType();
    evt.duration = button.wasPressedFor();

    if (instance->buttonQueue)
    {
        xQueueSend(instance->buttonQueue, &evt, 0); // non-blocking send
    }
}

/**
 * Long press detect handler
 * @param button button
 */
void ButtonModule::longPressDetect(Button2 &button)
{
    if (instance->longPressCallback)
    {
        instance->longPressCallback();
    }
}

/**
 * Set the function for the button event callbacks
 * @param callback the callback function
 */
void ButtonModule::setButtonCallback(void (*callback)(ButtonEvent))
{
    buttonCallback = callback;
}

/**
 * Set the function for the long press callback
 * @param callback the callback function
 */
void ButtonModule::setLongPressCallback(void(callback)(void))
{
    longPressCallback = callback;
}

/**
 * Get the button name
 * @return button name eg MENU
 */
String ButtonModule::getName(ButtonType button)
{
#define ENUM_CASE(x) \
    case BT_##x:     \
        return #x
    switch (button)
    {
        ENUM_CASE(BACK);
        ENUM_CASE(MENU);
        ENUM_CASE(UP);
        ENUM_CASE(DOWN);
    }
#undef ENUM_CASE
    return "UNKNOWN";
}

/**
 * Get the button event info
 * @return button event info string eg MENU - LONG_CLICK (534ms)
 */
String ButtonModule::getInfo(ButtonEvent buttonEvent)
{
    // Convert enums to strings
    String btnName;
    switch (buttonEvent.type)
    {
#define ENUM_CASE(x)  \
    case BT_##x:      \
        btnName = #x; \
        break
        ENUM_CASE(BACK);
        ENUM_CASE(MENU);
        ENUM_CASE(UP);
        ENUM_CASE(DOWN);
#undef ENUM_CASE
    default:
        btnName = "UNKNOWN_BTN";
        break;
    }

    String clickName;
    switch (buttonEvent.click)
    {
#define ENUM_CASE(x)    \
    case x:             \
        clickName = #x; \
        break
        ENUM_CASE(single_click);
        ENUM_CASE(double_click);
        ENUM_CASE(triple_click);
        ENUM_CASE(long_click);
        ENUM_CASE(empty);
#undef ENUM_CASE
    default:
        clickName = "unknown";
        break;
    }
    clickName.toUpperCase();

    // Format final string
    String info = btnName + " - " + clickName + " (" + String(buttonEvent.duration) + "ms)";
    return info;
}

/**
 * Configure pins before entering sleep
 */
void ButtonModule::configureWakeup()
{
    const uint64_t ignore = 0b11110001000000110000100111000010; // Ignore some GPIOs due to resets
    for (int i = 0; i < GPIO_NUM_MAX; i++)
    {
        if ((ignore >> i) & 0b1)
            continue;
        pinMode(i, INPUT);
    }

    esp_sleep_enable_ext1_wakeup(
        BTN_PIN_MASK,
        ESP_EXT1_WAKEUP_ANY_HIGH); // enable deep sleep wake on button press
}

/**
 * Handle the wakeup button event by simulating a click on the wakup button
 * @note if the button is still pressed then the click is not triggered
 */
void ButtonModule::handleWakeup()
{
    uint64_t wakeupBit = esp_sleep_get_ext1_wakeup_status();
    ButtonEvent event;
    event.type = BT_NONE;
    event.click = single_click;
    event.duration = 0;
    if (wakeupBit & MENU_BTN_MASK && !isPressed(BUTTON_MENU))
    {
        event.type = BT_MENU;
    }
    else if (wakeupBit & BACK_BTN_MASK && !isPressed(BUTTON_BACK))
    {
        event.type = BT_BACK;
    }
    else if (wakeupBit & UP_BTN_MASK && !isPressed(BUTTON_UP))
    {
        event.type = BT_UP;
    }
    else if (wakeupBit & DOWN_BTN_MASK && !isPressed(BUTTON_DOWN))
    {
        event.type = BT_DOWN;
    }
    if (event.type != BT_NONE)
    {
        if (buttonCallback)
            buttonCallback(event);
    }
}

/**
 * Check if button is being pressed
 * @param btn the button pin
 * @return whether pressed or not
 */
bool ButtonModule::isPressed(int btn)
{
    return digitalRead(btn);
}
